---
- hosts: prdx-docker13
  become: yes

  tasks:

    - name: install required packages
      yum:
        name: yum-utils
        state: latest

    - name: install packages
      yum:
        name: device-mapper-persistent-data
        state: latest

    - name: package install
      yum:
        name: lvm2
        state: latest

    - name: add docker repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      become: yes

    - name: install docker
      yum:
        name: docker-ce
        state: latest

    - name: install bridge-utils
      yum:
        name: bridge-utils
        state: latest

    - name: ensure docker is running
      service:
        name: docker
        state: started
        enabled: yes

