---
- hosts: webservers
  remote_user: ansible
  become: yes
  tasks:
  - name: install apache
    yum:
      name: httpd
      state: latest
  - name: create apache config file
    template:
     src: /srv/httpd.j2
     dest: /etc/httpd.conf
  - name: create index file
    template:
      src: /srv/index.j2
      dest: /var/www/html/index.html
  notify:
  - restart apache
  - name: start apache
    service:
      name: httpd
      state: started
  - name: enable apache
    service:
      name: httpd
      state: enabled
  handlers:
    - name: restart apache
      service:
        name:httpd
        state: restarted
