---
- hosts: pxe
  become: yes

  tasks:
  - name: install epel
    yum:
      name: epel-release
      state: latest

  - name: install nrpe
    yum:
      name: nrpe
      state: latest

  - name: install nagios plugins
    yum:
      name: nagios-plugins-all
      state: latest


  - name: start nrpe and enable it
    service:
      name: nrpe
      state: started
      enabled: yes

  - name: configure nagios server ip in config file
    lineinfile:
      path: /etc/nagios/nrpe.cfg
      regexp: '^allowed_hosts='
      line: allowed_hosts=127.0.0.1,192.168.43.18

